package com.konsol.core.domain;

import static com.konsol.core.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PlaystationDeviceTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceTypeAllPropertiesEquals(PlaystationDeviceType expected, PlaystationDeviceType actual) {
        assertPlaystationDeviceTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertPlaystationDeviceTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceTypeAllUpdatablePropertiesEquals(
        PlaystationDeviceType expected,
        PlaystationDeviceType actual
    ) {
        assertPlaystationDeviceTypeUpdatableFieldsEquals(expected, actual);
        assertPlaystationDeviceTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceTypeAutoGeneratedPropertiesEquals(
        PlaystationDeviceType expected,
        PlaystationDeviceType actual
    ) {
        assertThat(expected)
            .as("Verify PlaystationDeviceType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceTypeUpdatableFieldsEquals(PlaystationDeviceType expected, PlaystationDeviceType actual) {
        assertThat(expected)
            .as("Verify PlaystationDeviceType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e ->
                assertThat(e.getDefaultMainPrice())
                    .as("check defaultMainPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getDefaultMainPrice())
            )
            .satisfies(e -> assertThat(e.getProductId()).as("check productId").isEqualTo(actual.getProductId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceTypeUpdatableRelationshipsEquals(
        PlaystationDeviceType expected,
        PlaystationDeviceType actual
    ) {
        // empty method
    }
}
