package com.konsol.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlaystationDeviceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceAllPropertiesEquals(PlaystationDevice expected, PlaystationDevice actual) {
        assertPlaystationDeviceAutoGeneratedPropertiesEquals(expected, actual);
        assertPlaystationDeviceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceAllUpdatablePropertiesEquals(PlaystationDevice expected, PlaystationDevice actual) {
        assertPlaystationDeviceUpdatableFieldsEquals(expected, actual);
        assertPlaystationDeviceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceAutoGeneratedPropertiesEquals(PlaystationDevice expected, PlaystationDevice actual) {
        assertThat(expected)
            .as("Verify PlaystationDevice auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceUpdatableFieldsEquals(PlaystationDevice expected, PlaystationDevice actual) {
        assertThat(expected)
            .as("Verify PlaystationDevice relevant properties")
            .satisfies(e -> assertThat(e.getPk()).as("check pk").isEqualTo(actual.getPk()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getIndex()).as("check index").isEqualTo(actual.getIndex()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaystationDeviceUpdatableRelationshipsEquals(PlaystationDevice expected, PlaystationDevice actual) {
        // empty method
    }
}
