/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountUserSearchModel { 
    /**
     * Kind of user searching for
     */
    kind?: AccountUserSearchModel.KindEnum;
    /**
     * name of user searching for
     */
    name?: string;
    /**
     * phone of user searching for
     */
    phone?: string;
    /**
     * adress of user searching for
     */
    address?: string;
    /**
     * adress of user searching for
     */
    address_2?: string;
    page?: number;
    size?: number;
    id?: string;
}
export namespace AccountUserSearchModel {
    export type KindEnum = 'CUSTOMER' | 'SUPPLIER' | 'SALEMAN';
    export const KindEnum = {
        Customer: 'CUSTOMER' as KindEnum,
        Supplier: 'SUPPLIER' as KindEnum,
        Saleman: 'SALEMAN' as KindEnum
    };
}


