/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AccountUserSearchModel {
  /**
   * Kind of user searching for
   */
  kind?: AccountUserSearchModel.KindEnum;
  /**
   * name of user searching for
   */
  name?: string;
  /**
   * phone of user searching for
   */
  phone?: string;
  /**
   * adress of user searching for
   */
  address?: string;
  /**
   * adress of user searching for
   */
  address2?: string;
  page?: number;
  size?: number;
  id?: string;
}
export namespace AccountUserSearchModel {
  export type KindEnum = 'CUSTOMER' | 'SUPPLIER' | 'SALEMAN';
  export const KindEnum = {
    CUSTOMER: 'CUSTOMER' as KindEnum,
    SUPPLIER: 'SUPPLIER' as KindEnum,
    SALEMAN: 'SALEMAN' as KindEnum,
  };
}
