/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BankTransactionsDTO { 
    /**
     * Unique identifier for the transaction.
     */
    id?: string;
    /**
     * Primary key.
     */
    pk?: string;
    /**
     * Identifier for the associated bank.
     */
    bankId?: string;
    /**
     * Type of the source, e.g., \"INVOICE\" or \"MONEY\".
     */
    sourceType?: string;
    /**
     * Kind of the source.
     */
    sourceKind?: string;
    /**
     * Identifier for the source.
     */
    sourceId?: string;
    /**
     * Primary key of the source.
     */
    sourcePk?: string;
    /**
     * Amount of money coming in.
     */
    moneyIn?: number;
    /**
     * Amount of money going out.
     */
    moneyOut?: number;
    /**
     * Additional details about the transaction.
     */
    details?: string;
    /**
     * The date and time when the transaction was created.
     */
    createdDate?: string;
    /**
     * Identifier for the associated account.
     */
    accountId?: string;
    /**
     * Name of the associated account.
     */
    accountName?: string;
}

