/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChartDataDTO { 
    /**
     * Date in day/month/year format (التاريخ (يوم/شهر/سنة)).
     */
    date?: string;
    /**
     * Total sales (إجمالي المبيعات).
     */
    totalSales?: number;
    /**
     * Total quantity sold (إجمالي الكمية المباعة).
     */
    totalQty?: number;
    /**
     * Average price (متوسط السعر).
     */
    avgPrice?: number;
}

