/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * dto to create new money
 */
export interface CreateMoneyDTO { 
    kind: CreateMoneyDTO.KindEnum;
    details?: string;
    moneyIn?: number;
    moneyOut?: number;
    bankId?: string;
    accountId?: string;
}
export namespace CreateMoneyDTO {
    export type KindEnum = 'PAYMENT' | 'RECEIPT';
    export const KindEnum = {
        Payment: 'PAYMENT' as KindEnum,
        Receipt: 'RECEIPT' as KindEnum
    };
}


