/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateAccountUserDTO {
  name: string;
  kind?: CreateAccountUserDTO.KindEnum;
  balanceIn?: number;
  balanceOut?: number;
  phone?: string;
  address?: string;
  address2?: string;
}
export namespace CreateAccountUserDTO {
  export type KindEnum = 'CUSTOMER' | 'SUPPLIER' | 'SALEMAN';
  export const KindEnum = {
    CUSTOMER: 'CUSTOMER' as KindEnum,
    SUPPLIER: 'SUPPLIER' as KindEnum,
    SALEMAN: 'SALEMAN' as KindEnum,
  };
}
