/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * dto to create new money
 */
export interface CreateMoneyDTO {
  kind: CreateMoneyDTO.KindEnum;
  details?: string;
  moneyIn?: number;
  moneyOut?: number;
  bankId?: string;
  accountId?: string;
}
export namespace CreateMoneyDTO {
  export type KindEnum = 'PAYMENT' | 'RECEIPT';
  export const KindEnum = {
    PAYMENT: 'PAYMENT' as KindEnum,
    RECEIPT: 'RECEIPT' as KindEnum,
  };
}
