/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * model for creating new invoice items
 */
export interface CreateInvoiceItemDTO {
  id?: string;
  itemId: string;
  unitId?: string;
  qty?: number;
  price?: number;
}
