/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateAccountUserDTO {
  name: string;
  kind?: CreateAccountUserDTO.KindEnum;
  balanceIn?: number;
  balanceOut?: number;
  phone?: string;
  address?: string;
  address2?: string;
}
export namespace CreateAccountUserDTO {
  export type KindEnum = 'CUSTOMER' | 'SUPPLIER' | 'SALEMAN';
  export const KindEnum = {
    Customer: 'CUSTOMER' as KindEnum,
    Supplier: 'SUPPLIER' as KindEnum,
    Saleman: 'SALEMAN' as KindEnum,
  };
}
