/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeriesData } from './seriesData';


/**
 * Data Transfer Object for financial dashboard charts and visualizations. Supports various chart types including line, bar, pie, radar, and area charts.
 */
export interface FinancialChartDTO { 
    chartId?: string;
    title?: string;
    subtitle?: string;
    chartType?: string;
    xAxisLabel?: string;
    yAxisLabel?: string;
    labels?: Array<string>;
    series?: Array<SeriesData>;
    options?: { [key: string]: object; };
    metadata?: { [key: string]: string; };
    data?: Array<number>;
}

