/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceItemAnalysisDTO } from './invoiceItemAnalysisDTO';
import { StoreAccountAnalysisDTO } from './storeAccountAnalysisDTO';
import { PerformanceIndicatorsDTO } from './performanceIndicatorsDTO';
import { SalesMetricsDTO } from './salesMetricsDTO';
import { FinancialChartDTO } from './financialChartDTO';
import { CashFlowMetricsDTO } from './cashFlowMetricsDTO';
import { InvoiceAnalysisDTO } from './invoiceAnalysisDTO';

export interface FinancialDashboardDTO {
  salesMetrics?: SalesMetricsDTO;
  salesCharts?: Array<FinancialChartDTO>;
  cashFlowMetrics?: CashFlowMetricsDTO;
  cashFlowCharts?: Array<FinancialChartDTO>;
  invoiceAnalysis?: InvoiceAnalysisDTO;
  invoiceCharts?: Array<FinancialChartDTO>;
  invoiceItemAnalysis?: InvoiceItemAnalysisDTO;
  itemSalesCharts?: Array<FinancialChartDTO>;
  performanceIndicators?: PerformanceIndicatorsDTO;
  performanceCharts?: Array<FinancialChartDTO>;
  storeAccountAnalysis?: StoreAccountAnalysisDTO;
  analysisCharts?: Array<FinancialChartDTO>;
  startDate?: string;
  endDate?: string;
  storeId?: string;
  accountId?: string;
  bankId?: string;
}
