/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A model that contains all the elements that can be modified  in the invoice by requesting the modification
 */
export interface InvoiceUpdateDTO { 
    id?: string;
    discountPer?: number;
    discount?: number;
    additions?: number;
    additionsType?: string;
    expenses?: number;
    expensesType?: string;
    bankId?: string;
    accountId?: string;
    created_date?: string;
    storeId?: string;
    deferred?: boolean;
    userNetCost?: number;
    userNetPrice?: number;
}

