/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InvoiceItemViewDTO {
  pk?: string;
  id?: string;
  unit?: string;
  unitQtyIn?: number;
  unitQtyOut?: number;
  discount?: number;
  discountPer?: number;
  totalCost?: number;
  totalPrice?: number;
  qtyIn?: number;
  qtyOut?: number;
  netCost?: number;
  netPrice?: number;
  itemName?: string;
}
