/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * search with pagination , plain text , date [ from , to ]
 */
export interface InvoicesSearchModel { 
    page?: number;
    size?: number;
    sortField?: string;
    sortOrder?: string;
    searchText?: string;
    dateFrom?: string;
    dateTo?: string;
    kind?: InvoicesSearchModel.KindEnum;
    accountId?: string;
    storeId?: string;
    bankId?: string;
}
export namespace InvoicesSearchModel {
    export type KindEnum = 'ALL' | 'SALE' | 'PURCHASE';
    export const KindEnum = {
        All: 'ALL' as KindEnum,
        Sale: 'SALE' as KindEnum,
        Purchase: 'PURCHASE' as KindEnum
    };
}


