/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemSimpleDTO } from './itemSimpleDTO';

export interface InvoiceItemDTO {
  pk?: string;
  id?: string;
  unit?: string;
  unitPieces?: number;
  userQty?: number;
  unitQtyIn?: number;
  unitQtyOut?: number;
  unitCost?: number;
  unitPrice?: number;
  discountPer?: number;
  discount?: number;
  totalCost?: number;
  totalPrice?: number;
  qtyIn?: number;
  qtyOut?: number;
  cost?: number;
  price?: number;
  netCost?: number;
  netPrice?: number;
  item?: ItemSimpleDTO;
}
