/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A model that contains all the elements that can be modified  in the invoice by requesting the modification
 */
export interface InvoiceUpdateDTO {
  id?: string;
  discountPer?: number;
  discount?: number;
  additions?: number;
  additionsType?: string;
  expenses?: number;
  expensesType?: string;
  bankId?: string;
  accountId?: string;
  createdDate?: Date;
  storeId?: string;
  deferred?: boolean;
}
