/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * search with pagination , plain text , date [ from , to ]
 */
export interface InvoicesSearchModel {
  page?: number;
  size?: number;
  sortField?: string;
  sortOrder?: string;
  searchText?: string;
  dateFrom?: string;
  dateTo?: string;
  kind?: InvoicesSearchModel.KindEnum;
  accountId?: string;
  storeId?: string;
  bankId?: string;
}
export namespace InvoicesSearchModel {
  export type KindEnum = 'ALL' | 'SALE' | 'PURCHASE';
  export const KindEnum = {
    ALL: 'ALL' as KindEnum,
    SALE: 'SALE' as KindEnum,
    PURCHASE: 'PURCHASE' as KindEnum,
  };
}
