/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InvoiceItemViewDTO {
  pk?: string;
  id?: string;
  unit?: string;
  unitQtyIn?: number;
  unitQtyOut?: number;
  discount?: number;
  discountPer?: number;
  totalCost?: number;
  totalPrice?: number;
  qtyIn?: number;
  qtyOut?: number;
  netCost?: number;
  netPrice?: number;
  itemName?: string;
}
