/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemPriceOptionDTO } from './itemPriceOptionDTO';

/**
 * It is used to display the item in the inventory view
 */
export interface ItemViewDTO {
  id?: string;
  pk?: number;
  name: string;
  barcode?: string;
  price1?: string;
  price2?: string;
  category?: string;
  qty?: number;
  cost?: number;
  createdBy?: string;
  createdDate?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  checkQty?: boolean;
  PriceOptions?: Array<ItemPriceOptionDTO>;
}
