/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data Transfer Object for item profitability metrics
 */
export interface ItemProfitabilityDTO { 
    /**
     * Unique identifier of the item
     */
    itemId?: string;
    /**
     * Name of the item
     */
    itemName?: string;
    /**
     * Total revenue generated by the item
     */
    totalRevenue?: number;
    /**
     * Total cost of the item
     */
    totalCost?: number;
    /**
     * Gross profit (revenue - cost)
     */
    grossProfit?: number;
    /**
     * Profit margin percentage
     */
    profitMargin?: number;
    /**
     * Number of units sold
     */
    salesVolume?: number;
    /**
     * Average selling price
     */
    averagePrice?: number;
    /**
     * Average cost per unit
     */
    averageCost?: number;
}

