/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KonsolGridBand } from './konsolGridBand';
import { KonsolGridColumn } from './konsolGridColumn';


export interface KonsolGridOptions { 
    id?: string;
    name?: string;
    allowBands?: boolean;
    showSearch?: boolean;
    showGroupSearch?: boolean;
    sortField?: string;
    columns?: Array<KonsolGridColumn>;
    bands?: Array<KonsolGridBand>;
    rowHeight?: number;
    showCurrency?: boolean;
}

