/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicenseDTOHardwareIdentifiers } from './licenseDTOHardwareIdentifiers';


/**
 * Data Transfer Object for software license information
 */
export interface LicenseDTO { 
    /**
     * Unique identifier for the client
     */
    clientId?: string;
    /**
     * License activation key
     */
    licenseKey?: string;
    /**
     * License expiration date and time
     */
    expiryDate?: string;
    hardwareIdentifiers?: LicenseDTOHardwareIdentifiers;
}

