/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Hardware identifiers used for license validation
 */
export interface LicenseDTOHardwareIdentifiers { 
    /**
     * CPU identifier
     */
    processorIdentifier?: string;
    /**
     * CPU architecture
     */
    processorArchitecture?: string;
    /**
     * CPU architecture (32/64 bit)
     */
    processorArchitew6432?: string;
    /**
     * Number of CPU processors
     */
    numberOfProcessors?: string;
    /**
     * Motherboard serial number
     */
    motherboardSerialNumber?: string;
    /**
     * BIOS serial number
     */
    biosSerialNumber?: string;
    /**
     * Disk drive serial number
     */
    diskDriveSerialNumber?: string;
}

