/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankDTO } from './bankDTO';
import { ItemDTO } from './itemDTO';
import { AccountUserDTO } from './accountUserDTO';

export interface MoneyDTO {
  pk?: string;
  id?: string;
  kind?: MoneyDTO.KindEnum;
  details?: string;
  moneyIn?: number;
  moneyOut?: number;
  bank?: BankDTO;
  item?: ItemDTO;
  account?: AccountUserDTO;
  created_date?: string;
}
export namespace MoneyDTO {
  export type KindEnum = 'PAYMENT' | 'RECEIPT';
  export const KindEnum = {
    Payment: 'PAYMENT' as KindEnum,
    Receipt: 'RECEIPT' as KindEnum,
  };
}
