/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountUserDTO } from './accountUserDTO';
import { BankDTO } from './bankDTO';
import { ItemDTO } from './itemDTO';

export interface MoneyDTO {
  pk?: string;
  id?: string;
  kind?: MoneyDTO.KindEnum;
  details?: string;
  moneyIn?: number;
  moneyOut?: number;
  bank?: BankDTO;
  item?: ItemDTO;
  account?: AccountUserDTO;
  createdDate?: Date;
}
export namespace MoneyDTO {
  export type KindEnum = 'PAYMENT' | 'RECEIPT';
  export const KindEnum = {
    PAYMENT: 'PAYMENT' as KindEnum,
    RECEIPT: 'RECEIPT' as KindEnum,
  };
}
