/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoneyDTO } from './moneyDTO';

export interface MoniesViewDTOContainer {
  result?: Array<MoneyDTO>;
  totalMoneyIn?: number;
  totalMoneyOut?: number;
  total?: number;
}
