/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * search Monies with pagination , plain text , date [ from , to ] also account and bank
 */
export interface MoniesSearchModel {
  /**
   * search for single money instance
   */
  id?: string;
  pk?: string;
  page?: number;
  size?: number;
  sortField?: string;
  sortOrder?: MoniesSearchModel.SortOrderEnum;
  /**
   * text to seach for
   */
  kind?: MoniesSearchModel.KindEnum;
  /**
   * date form to seach for or null
   */
  dateFrom?: string;
  /**
   * date to to seach for or null
   */
  dateTo?: string;
  accountId?: string;
  bankId?: string;
  details?: string;
}
export namespace MoniesSearchModel {
  export type SortOrderEnum = 'DESC' | 'ASC';
  export const SortOrderEnum = {
    DESC: 'DESC' as SortOrderEnum,
    ASC: 'ASC' as SortOrderEnum,
  };
  export type KindEnum = 'RECEIPT' | 'PAYMENT';
  export const KindEnum = {
    RECEIPT: 'RECEIPT' as KindEnum,
    PAYMENT: 'PAYMENT' as KindEnum,
  };
}
