/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PerformanceMetricsDTO {
  totalRevenue?: number;
  averageInvoiceValue?: number;
  grossProfit?: number;
  grossProfitMargin?: number;
  operatingExpenses?: number;
  operatingProfit?: number;
  operatingProfitMargin?: number;
  netProfit?: number;
  netProfitMargin?: number;
  revenueGrowth?: number;
  totalTransactions?: number;
  /**
   * Map of additional metric names to values
   */
  additionalMetrics?: { [key: string]: number };
}
