/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * OpenAPI spec version: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PkDTO {
  id?: string;
  kind?: PkDTO.KindEnum;
  value?: number;
}
export namespace PkDTO {
  export type KindEnum = 'INVOICE' | 'InvoicesItems' | 'Money';
  export const KindEnum = {
    INVOICE: 'INVOICE' as KindEnum,
    InvoicesItems: 'InvoicesItems' as KindEnum,
    Money: 'Money' as KindEnum,
  };
}
