/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PkDTO {
  id?: string;
  kind?: PkDTO.KindEnum;
  value?: number;
}
export namespace PkDTO {
  export type KindEnum = 'INVOICE' | 'InvoicesItems' | 'Money';
  export const KindEnum = {
    Invoice: 'INVOICE' as KindEnum,
    InvoicesItems: 'InvoicesItems' as KindEnum,
    Money: 'Money' as KindEnum,
  };
}
