/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A model representing a Playstation container.
 */
export interface PlaystationContainer { 
    /**
     * The unique identifier for the Playstation container.
     */
    id?: string;
    /**
     * The name of the Playstation container.
     */
    name: string;
    /**
     * The category of the Playstation container.
     */
    category: string;
    /**
     * The default icon for the Playstation container.
     */
    defaultIcon?: string;
    /**
     * Indicates if time management is enabled.
     */
    hasTimeManagement: boolean;
    /**
     * Indicates if the type is shown.
     */
    showType: boolean;
    /**
     * Indicates if time is shown.
     */
    showTime: boolean;
    /**
     * Indicates if devices can be moved.
     */
    canMoveDevice: boolean;
    /**
     * Indicates if multiple time management options are supported.
     */
    canHaveMultiTimeManagement: boolean;
    /**
     * Accepted order categories.
     */
    acceptedOrderCategories: Array<string>;
    /**
     * Selected price category for orders.
     */
    orderSelectedPriceCategory: string;
}

