/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PsDeviceType } from './psDeviceType';
import { InvoiceDTO } from './invoiceDTO';

export interface PsSessionDTO {
  id?: string;
  startTime?: string;
  invoice?: InvoiceDTO;
  type?: PsDeviceType;
  deviceSessions?: Array<PsSessionDTO>;
  deviceSessionsNetPrice?: number;
}
