/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceDTO } from './invoiceDTO';
import { PsDeviceDTO } from './psDeviceDTO';

/**
 *
 */
export interface PsSessionDTO {
  id?: string;
  active?: boolean;
  startTime?: string;
  endTime?: string;
  device?: PsDeviceDTO;
  invoice?: InvoiceDTO;
}
