/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SheftDTO {
  id?: string;
  startTime?: string;
  endTime?: string;
  active?: boolean;
  assignedEmployee?: string;
  duration?: string;
  totalprice?: number;
  totalCost?: number;
  netPrice?: number;
  netCost?: number;
  netUserPrice?: number;
  totalItemsOut?: number;
  discount?: number;
  invoicesAdditions?: number;
  additions?: number;
  additionsNotes?: number;
  invoicesExpenses?: number;
  sheftExpenses?: number;
  totalinvoices?: number;
  totaldeletedItems?: number;
  totaldeletedItemsPrice?: number;
  notes?: string;
}
