/**
 * Konsol Core API
 * Konsol Core API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: adel50ali50@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetricValue } from './metricValue';
import { TrendPoint } from './trendPoint';


export interface TopPerformerDTO { 
    id?: string;
    name?: string;
    category?: string;
    totalRevenue?: number;
    totalProfit?: number;
    profitMargin?: number;
    transactionCount?: number;
    averageTransactionValue?: number;
    trend?: Array<TrendPoint>;
    metrics?: Array<MetricValue>;
}

