export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  ACCOUNTANT = 'ROLE_ACCOUNTANT',
  INVENTORY_MANAGER = 'ROLE_INVENTORY_MANAGER',
  PURCHASE_MANAGER = 'ROLE_PURCHASE_MANAGER',
  SALES_MANAGER = 'ROLE_SALES_MANAGER',
}
